# The hash of first block in a chain to know with which nodes to work
origin = "0AE588D62D710422A7972EA1E8A659CC8E93DB59489ACE32C499CD279B000000"
# A path to your key file to load automatically
key_file = "default.key"
# How many last blocks to check on start
check_blocks = 8

# Network settings
[net]
# All bootstap nodes
peers = []
# Your node will listen on that address for other nodes to connect
listen = "[::]:46866"
# Set true if you want your IP to participate in peer-exchange, or false otherwise
public = true
# Allow connections to/from Yggdrasil only (https://yggdrasil-network.github.io)
yggdrasil_only = false

# DNS resolver options
[dns]
# Your DNS resolver will be listening on this address and port (Usual port is 53)
listen = "127.0.0.1:53"
# How many threads to spawn by DNS server
threads = 20
# AdGuard DNS servers to filter ads and trackers
forwarders = ["94.140.14.14:53", "94.140.15.15:53"]
# Cloudflare servers
#forwarders = ["1.1.1.1:53", "1.0.0.1:53"]

# Hosts file support (resolve local names or block ads)
#hosts = ["system", "adblock.txt"]

#Mining options
[mining]
# How many CPU threads to spawn for mining, zero = number of CPU cores
threads = 0
# Set lower priority for mining threads
lower = true
