#!/bin/sh

# This is the "Service" file for GIS in OPKG environment
# Usually lives in /opt/etc/init.d/ directory

ENABLED=yes
PROCS=gis
ARGS="-d -c /opt/etc/gis.conf -w /opt/var/lib/gis/ -l /opt/var/log/gis.log"
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
